"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2p!^vllp-o81sxg3lc#7eq5r_j-+m#hrnhog=y%3&z%rua-hws'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1',"lingora-learning-platform.onrender.com"]


# Application definition

INSTALLED_APPS = [
    'corsheaders'
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'accounts',
    'academics',
    'assessments',
    'progress',
    'tutor',
    'notifications',
    'community',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000","https://lingora-learning-platform-1.onrender.com"
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'recommendation_refresh': '5/hour',
        'assessment_create': '30/hour',
        'assessment_complete': '20/hour',
    },
}

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
}
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_USER_MODEL = 'accounts.User'



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Email backend configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Previous Hugging Face model setting:
# HF_LESSON_MODEL = os.getenv('HF_LESSON_MODEL', 'Qwen/Qwen3-8B')
GROQ_LESSON_MODEL = os.getenv('GROQ_LESSON_MODEL', 'llama-3.3-70b-versatile')

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'socket_connect_timeout': float(os.getenv('CELERY_BROKER_CONNECT_TIMEOUT', '2')),
    'socket_timeout': float(os.getenv('CELERY_BROKER_SOCKET_TIMEOUT', '5')),
}
CELERY_BEAT_SCHEDULE = {
    'retry-failed-lessons': {
        'task': 'academics.tasks.retry_failed_lesson_generations',
        'schedule': int(os.getenv('LESSON_RETRY_INTERVAL_SECONDS', '300')),
    },
    'send-daily-learning-reminders': {
        'task': 'notifications.tasks.send_daily_learning_reminders',
        'schedule': int(os.getenv('NOTIFICATION_DAILY_REMINDER_INTERVAL_SECONDS', '3600')),
    },
    'send-streak-risk-notifications': {
        'task': 'notifications.tasks.send_streak_risk_notifications',
        'schedule': int(os.getenv('NOTIFICATION_STREAK_INTERVAL_SECONDS', '3600')),
    },
    'send-inactivity-notifications': {
        'task': 'notifications.tasks.send_inactivity_notifications',
        'schedule': int(os.getenv('NOTIFICATION_INACTIVITY_INTERVAL_SECONDS', '86400')),
    },
    'send-assessment-reminders': {
        'task': 'notifications.tasks.send_assessment_reminders',
        'schedule': int(os.getenv('NOTIFICATION_ASSESSMENT_INTERVAL_SECONDS', '3600')),
    },
    'send-lesson-ready-notifications': {
        'task': 'notifications.tasks.send_lesson_ready_notifications',
        'schedule': int(os.getenv('NOTIFICATION_LESSON_READY_INTERVAL_SECONDS', '900')),
    },
    'clean-expired-notifications': {
        'task': 'notifications.tasks.clean_expired_notifications',
        'schedule': int(os.getenv('NOTIFICATION_CLEANUP_INTERVAL_SECONDS', '86400')),
    },
}
LESSON_GENERATION_VERSION = int(os.getenv('LESSON_GENERATION_VERSION', '1'))
LESSON_PROMPT_VERSION = os.getenv('LESSON_PROMPT_VERSION', 'lesson-v1')
LESSON_GENERATION_MAX_RETRIES = int(os.getenv('LESSON_GENERATION_MAX_RETRIES', '3'))
LESSON_GENERATION_TTL_SECONDS = int(os.getenv('LESSON_GENERATION_TTL_SECONDS', '604800'))
LESSON_GENERATION_FALLBACK_SECONDS = float(
    os.getenv('LESSON_GENERATION_FALLBACK_SECONDS', '0')
)
ADAPTIVE_RECENT_WEIGHT = float(os.getenv('ADAPTIVE_RECENT_WEIGHT', '0.30'))
ADAPTIVE_PATH_LENGTH = int(os.getenv('ADAPTIVE_PATH_LENGTH', '7'))
ADAPTIVE_GENERATION_BUFFER = int(os.getenv('ADAPTIVE_GENERATION_BUFFER', '2'))

# Optional local diagnostics for Groq lesson generation attempts.
LLM_GENERATION_LOGGING_ENABLED = True
LLM_GENERATION_LOG_PROMPTS = True
