# Generated by Django 6.0.7 on 2026-07-09 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('order_no', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order_no', 'min_score'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('explanation_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanation_curricula', to='academics.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_curricula', to='academics.language')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('target_language', 'explanation_language')},
            },
        ),
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order_no', models.PositiveIntegerField(default=1)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='academics.curriculum')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_categories', to='academics.difficultylevel')),
            ],
            options={
                'verbose_name_plural': 'lesson categories',
                'ordering': ['order_no', 'name'],
                'unique_together': {('curriculum', 'level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order_no', models.PositiveIntegerField(default=1)),
                ('estimated_minutes', models.PositiveIntegerField(default=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academics.lessoncategory')),
            ],
            options={
                'ordering': ['order_no', 'title'],
                'unique_together': {('category', 'title')},
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_text', models.TextField()),
                ('explanation_text', models.TextField()),
                ('example_text', models.TextField()),
                ('audio_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('explanation_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanation_lesson_contents', to='academics.language')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='academics.lesson')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_lesson_contents', to='academics.language')),
            ],
            options={
                'ordering': ['lesson__order_no', 'title'],
                'unique_together': {('lesson', 'target_language', 'explanation_language')},
            },
        ),
    ]
