# Generated by Django 6.0.6 on 2026-07-25 17:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_skill_profiles(apps, schema_editor):
    LearnerProfile = apps.get_model('accounts', 'LearnerProfile')
    SkillProfile = apps.get_model('academics', 'LearnerSkillProfile')
    for learner in LearnerProfile.objects.select_related('current_level').iterator():
        level = learner.current_level
        score = round((level.min_score + level.max_score) / 2) if level else 50
        SkillProfile.objects.get_or_create(
            user_id=learner.user_id,
            defaults={**{f'{skill}_score': score for skill in
                         ('reading', 'writing', 'listening', 'speaking', 'vocabulary', 'grammar')},
                      'overall_score': score, 'confidence': 10},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_generatedlesson_xp_earned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityattempt',
            name='maximum_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='activityattempt',
            name='normalized_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='activityattempt',
            name='obtained_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='generatedlesson',
            name='personalization_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lesson',
            name='maximum_recommended_proficiency',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='minimum_recommended_proficiency',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='LearnerSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_score', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('writing_score', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('listening_score', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('speaking_score', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vocabulary_score', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grammar_score', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence', models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_completed_lessons', models.PositiveIntegerField(default=0)),
                ('total_activity_attempts', models.PositiveIntegerField(default=0)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('focus_skills', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('replaced', 'Replaced'), ('paused', 'Paused')], default='active', max_length=20)),
                ('engine_version', models.CharField(default='deterministic_v1', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='academics.curriculum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_paths', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveIntegerField()),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='locked', max_length=20)),
                ('recommendation_score_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('reason_snapshot', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_items', to='academics.lesson')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academics.learningpath')),
            ],
            options={
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='LessonPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='academics.lesson')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_links', to='academics.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', through='academics.LessonPrerequisite', to='academics.lesson'),
        ),
        migrations.CreateModel(
            name='LessonRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('priority', models.PositiveIntegerField()),
                ('primary_skill', models.CharField(blank=True, max_length=20)),
                ('reason', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('engine_version', models.CharField(default='deterministic_v1', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='academics.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20)),
                ('previous_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_change', models.DecimalField(decimal_places=2, max_digits=6)),
                ('source_type', models.CharField(choices=[('assessment', 'Assessment'), ('lesson', 'Lesson'), ('backfill', 'Backfill')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='learningpath',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'curriculum'), name='one_active_path_per_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='learningpathitem',
            constraint=models.UniqueConstraint(fields=('path', 'order_no'), name='unique_path_order'),
        ),
        migrations.AddConstraint(
            model_name='learningpathitem',
            constraint=models.UniqueConstraint(fields=('path', 'lesson'), name='unique_lesson_in_path'),
        ),
        migrations.AddConstraint(
            model_name='lessonprerequisite',
            constraint=models.UniqueConstraint(fields=('lesson', 'prerequisite'), name='unique_lesson_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='lessonprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('lesson', models.F('prerequisite')), _negated=True), name='lesson_not_own_prerequisite'),
        ),
        migrations.AddIndex(
            model_name='lessonrecommendation',
            index=models.Index(fields=['user', 'status', 'priority'], name='academics_l_user_id_25dc2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'lesson', 'engine_version'), name='unique_pending_recommendation'),
        ),
        migrations.RunPython(backfill_skill_profiles, migrations.RunPython.noop),
    ]
