# Generated by Django 6.0.6 on 2026-08-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_one_active_path_per_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncontent',
            options={'ordering': ['lesson', 'order_no']},
        ),
        migrations.AlterUniqueTogether(
            name='lessoncontent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='order_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='lessoncontent',
            constraint=models.UniqueConstraint(fields=('lesson', 'order_no'), name='unique_lesson_content_order'),
        ),
    ]
