# Generated by Django 6.0.6 on 2026-08-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_427e4b_idx',
            old_name='notificatio_user_id_082d41_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_ef3643_idx',
            old_name='notificatio_user_id_48b8ca_idx',
        ),
    ]
