# Generated by Django 6.0.7 on 2026-07-09 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('comprehension', 'Comprehension')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('explanation_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanation_assessments', to='academics.language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.difficultylevel')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_assessments', to='academics.language')),
            ],
            options={
                'ordering': ['level__order_no', 'type', 'title'],
                'unique_together': {('target_language', 'explanation_language', 'level', 'type')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('short_answer', 'Short Answer')], default='mcq', max_length=20)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('order_no', models.PositiveIntegerField(default=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment')),
            ],
            options={
                'ordering': ['order_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order_no', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.assessmentquestion')),
            ],
            options={
                'ordering': ['order_no', 'id'],
            },
        ),
    ]
