# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquestion',
            name='question_type',
            field=models.CharField(
                choices=[
                    ('mcq', 'MCQ'),
                    ('passage_mcq', 'Passage MCQ'),
                    ('short_answer', 'Short Answer'),
                ],
                default='mcq',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='passage_hint_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='passage_hint_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='passage_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='passage_read_time',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='passage_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='passage_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
