# Generated by Codex on 2026-07-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentquestion_passage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('label', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('read_time', models.CharField(blank=True, max_length=40)),
                ('hint_title', models.CharField(blank=True, max_length=120)),
                ('hint_text', models.CharField(blank=True, max_length=255)),
                ('order_no', models.PositiveIntegerField(default=1)),
                (
                    'assessment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='passages',
                        to='assessments.assessment',
                    ),
                ),
            ],
            options={
                'ordering': ['order_no', 'id'],
            },
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='passage',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='questions',
                to='assessments.passage',
            ),
        ),
    ]
