# Generated by Django 6.0.6 on 2026-07-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_passage_assessmentquestion_passage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='passage_hint_text',
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='passage_hint_title',
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='passage_label',
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='passage_read_time',
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='passage_text',
        ),
    ]
