# Generated by Django 6.0.6 on 2026-07-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_remove_assessmentquestion_passage_hint_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquestion',
            name='marks',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
